# Generated by Django 3.0 on 2021-08-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customer_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cust_code', models.CharField(max_length=200, null=True)),
                ('Ref_cust_code', models.CharField(max_length=200, null=True)),
                ('Table_name', models.CharField(max_length=200, null=True)),
                ('ApplicationName', models.CharField(max_length=200, null=True)),
                ('status', models.BooleanField(default=1, null=True)),
            ],
        ),
    ]
