# Generated by Django 3.0 on 2021-08-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='Ref_cust_code',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
